<script setup lang="ts">
import { AudioLines, Languages, MessageCircle, Scissors, Workflow } from "lucide-vue-next";
import beeBot from "@/assets/images/magic-reply/bee-bot.png";
import customer from "@/assets/images/magic-reply/customer-service-agent-7.png";
import diagram from "@/assets/images/workflows/diagram.png";
import dotGrid from "@/assets/images/workflows/dot-grid.svg";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

const tabs = [
  { id: "reply", label: "Reply", icon: MessageCircle },
  { id: "transcribe", label: "Transcribe", icon: AudioLines },
  { id: "translate", label: "Translate", icon: Languages },
  { id: "summarize", label: "Summarize", icon: Scissors },
  { id: "categorize", label: "Categorize", icon: Workflow },
];
</script>

<template>
  <div class="px-6 lg:px-8">
    <div class="relative mx-auto max-w-7xl">
      <section
        aria-labelledby="magic-reply-title"
        class="dark relative isolate z-10 rounded-2xl border-2 bg-background px-6 py-12 text-foreground sm:rounded-3xl sm:px-12 lg:py-24"
      >
        <svg
          aria-hidden="true"
          viewBox="0 0 1280 776"
          preserveAspectRatio="none"
          class="pointer-events-none absolute inset-0 -z-10 size-full rounded-2xl text-border sm:rounded-3xl"
        >
          <path
            d="M100 0V40Q100 60 120 80L145 108Q162 125 162 145V776M1180 0V40Q1180 60 1160 80L1135 108Q1118 125 1118 145V640Q1118 660 1138 680L1160 704Q1180 722 1180 742V776"
            fill="none"
            stroke="currentColor"
          />
        </svg>
        <div
          aria-hidden="true"
          class="pointer-events-none absolute inset-y-40 left-16 hidden w-12 bg-repeat opacity-40 lg:block"
          :style="{ backgroundImage: `url(${dotGrid})` }"
        />
        <div
          aria-hidden="true"
          class="pointer-events-none absolute inset-y-40 right-16 hidden w-12 bg-repeat opacity-40 lg:block"
          :style="{ backgroundImage: `url(${dotGrid})` }"
        />
        <Tabs
          default-value="reply"
          class="mx-auto max-w-2xl"
        >
          <div class="overflow-x-auto pb-2">
            <TabsList
              aria-label="AI capabilities"
              class="mx-auto flex h-12 rounded-full bg-black/20 p-1"
            >
              <TabsTrigger
                v-for="item in tabs"
                :key="item.id"
                :value="item.id"
                class="gap-2 rounded-full px-4 text-base"
              >
                <component
                  :is="item.icon"
                  aria-hidden="true"
                  class="size-5"
                />
                {{ item.label }}
              </TabsTrigger>
            </TabsList>
          </div>
          <TabsContent
            v-for="item in tabs"
            :key="item.id"
            :value="item.id"
            class="my-8 min-h-64 sm:my-12 md:my-16 lg:my-20"
          >
            <template v-if="item.id === 'reply'">
              <div class="flex items-end gap-2 sm:ml-8">
                <img
                  :src="customer"
                  alt="Customer"
                  width="200"
                  height="200"
                  loading="lazy"
                  class="size-8 shrink-0 rounded-full"
                >
                <p class="max-w-120 rounded-xl border bg-white/15 p-4 font-noto text-lg/7 text-muted-foreground">
                  Hi, I’m having trouble tracking my recent order.<br>
                  The tracking number isn’t showing any information.
                </p>
              </div>
              <div class="mt-4 ml-10 max-w-130 rounded-xl border border-cyan-400/15 bg-cyan-400/10 p-4 font-noto text-base/7 text-cyan-400 sm:ml-26">
                <p class="mb-1 font-medium">
                  Generated by MagicReply (not sent yet):
                </p>
                <p>I’m sorry to hear that you’re having issues tracking your order. Could you please provide me with your order number ?</p>
              </div>
            </template>
            <div
              v-else
              class="mx-auto max-w-130 rounded-xl border bg-card p-6 text-lg/7 text-muted-foreground"
            >
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
            </div>
          </TabsContent>
        </Tabs>
        <h2
          id="magic-reply-title"
          class="relative mx-auto text-center text-subtitle sm:text-title lg:text-5xl/14"
        >
          Leverage the power of AI<br>with <span class="bg-linear-to-r from-cyan-200 via-cyan-400 to-primary bg-clip-text text-transparent">MagicReply</span>
        </h2>
        <img
          :src="beeBot"
          alt="A Crisp teammate accompanied by a flying assistant bot."
          width="370"
          height="379"
          loading="lazy"
          class="pointer-events-none absolute -bottom-28 -left-4 z-10 hidden h-auto w-64 md:block lg:-bottom-40 lg:w-92"
        >
      </section>

      <section
        aria-labelledby="workflows-title"
        class="relative isolate mt-4 overflow-hidden rounded-2xl bg-muted px-6 pt-12 pb-16 sm:rounded-3xl sm:px-12 lg:pb-24"
      >
        <div
          aria-hidden="true"
          class="pointer-events-none absolute inset-0 -z-10 mask-radial-from-20% mask-radial-to-70% bg-repeat"
          :style="{ backgroundImage: `url(${dotGrid})` }"
        />
        <img
          :src="diagram"
          alt="An automated bot workflow branches into Tech and Sales, then sends the customer to the relevant team."
          width="1492"
          height="1022"
          loading="lazy"
          class="mx-auto h-auto w-full max-w-188"
        >
        <h2
          id="workflows-title"
          class="-mt-4 text-center text-subtitle sm:text-title lg:text-5xl/14"
        >
          Create your dream workflows<br class="hidden sm:block"> with automated bots
        </h2>
      </section>
    </div>
  </div>
</template>
