<script setup lang="ts">
import customer from "@/assets/images/magic-reply/customer-service-agent-7.png";

const conversation = useTemplateRef<HTMLDivElement>("conversation");
const { messageClasses, visibleMessages } = useConversationAnimation(conversation, [0, 1200]);
</script>

<template>
  <div
    ref="conversation"
    role="img"
    aria-label="A customer asks for help tracking their order. MagicReply generates a suggested response asking for the order number, which has not been sent yet."
  >
    <div aria-hidden="true">
      <div
        class="flex items-end gap-2 sm:ml-8"
        :class="messageClasses"
        :data-visible="visibleMessages >= 1"
      >
        <img
          :src="customer"
          alt=""
          width="200"
          height="200"
          loading="lazy"
          class="size-8 shrink-0 rounded-full"
        >
        <p class="max-w-120 rounded-xl border bg-white/15 p-4 font-noto text-lg/7 text-muted-foreground">
          Hi, I’m having trouble tracking my recent order.<br>
          The tracking number isn’t showing any information.
        </p>
      </div>
      <div
        class="mt-4 ml-10 max-w-130 rounded-xl border border-cyan-400/15 bg-cyan-400/10 p-4 font-noto text-base/7 text-cyan-400 sm:ml-26"
        :class="messageClasses"
        :data-visible="visibleMessages >= 2"
      >
        <p class="mb-1 font-medium">
          Generated by MagicReply (not sent yet):
        </p>
        <p>I’m sorry to hear that you’re having issues tracking your order. Could you please provide me with your order number ?</p>
      </div>
    </div>
  </div>
</template>
